// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserEfCore.Data;

#nullable disable

namespace UserEfCore.Migrations
{
    [DbContext(typeof(PhoneListingDbContext))]
    [Migration("20230720133540_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UserEfCore.Data.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PhoneNumber = "555 55 55",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            PhoneNumber = "512355",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            PhoneNumber = "33333",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            PhoneNumber = "4444455",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            PhoneNumber = "990900",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("UserEfCore.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ata"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cem abi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Faruk abi"
                        });
                });

            modelBuilder.Entity("UserEfCore.Data.Phone", b =>
                {
                    b.HasOne("UserEfCore.Data.User", "User")
                        .WithMany("Phones")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserEfCore.Data.User", b =>
                {
                    b.Navigation("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
